// ecual/src/ecual_gpio_config.c

#include "ecual_gpio_config.h" // Includes ecual_gpio.h for ECUAL_GPIO_Config_t definition

// Definition of the static constant array for GPIO pin configurations
const ECUAL_GPIO_Config_t gpio_pin_configurations[] = {
    // Example configurations for all pins previously defined symbolically:
    {ECUAL_GPIO_OUT_PIN_1,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_2,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_3,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_4,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_5,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_6,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_7,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_8,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_9,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_OUT_PIN_10, ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},

    {ECUAL_GPIO_ALARM_PIN,  ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},

    {ECUAL_GPIO_KEYPAD_ROW_1, ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_KEYPAD_ROW_2, ECUAL_GPIO_DIR_OUTPUT, ECUAL_GPIO_PULL_NONE, ECUAL_GPIO_STATE_LOW},
    {ECUAL_GPIO_KEYPAD_COL_1, ECUAL_GPIO_DIR_INPUT,  ECUAL_GPIO_PULL_UP,   ECUAL_GPIO_STATE_DEFAULT},
    {ECUAL_GPIO_KEYPAD_COL_2, ECUAL_GPIO_DIR_INPUT,  ECUAL_GPIO_PULL_UP,   ECUAL_GPIO_STATE_DEFAULT},
};

// Definition of the number of configurations in the array
const uint32_t ECUAL_NUM_GPIO_CONFIGURATIONS = sizeof(gpio_pin_configurations) / sizeof(ECUAL_GPIO_Config_t);
